-- 系统用户表
CREATE TABLE TB_S_USER (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '用户 ID',
    USERNAME VARCHAR(50) NOT NULL COMMENT '用户名',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '密码 (BCrypt 加密)',
    REAL_NAME VARCHAR(100) COMMENT '真实姓名',
    AVATAR VARCHAR(500) COMMENT '头像 URL',
    ORGANIZATION VARCHAR(200) COMMENT '所属学校/机构',
    PHONE VARCHAR(20) COMMENT '手机号',
    EMAIL VARCHAR(100) COMMENT '邮箱',
    USER_TYPE VARCHAR(10) DEFAULT 'TEACHER' COMMENT '用户类型：TEACHER/STUDENT',
    STATUS VARCHAR(10) DEFAULT 'NORMAL' COMMENT '状态：NORMAL/LOCKED',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间',
    GXR VARCHAR(32) COMMENT '更新人',
    GXSJ DATETIME COMMENT '更新时间',
    LJSC INT DEFAULT 0 COMMENT '逻辑删除（0：显示，1：隐藏）'
) COMMENT '系统用户表';

-- 系统角色表
CREATE TABLE TB_S_ROLE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '角色 ID',
    ROLE_CODE VARCHAR(50) NOT NULL COMMENT '角色编码',
    ROLE_NAME VARCHAR(100) NOT NULL COMMENT '角色名称',
    REMARK VARCHAR(255) COMMENT '备注',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间',
    GXR VARCHAR(32) COMMENT '更新人',
    GXSJ DATETIME COMMENT '更新时间',
    LJSC INT DEFAULT 0 COMMENT '逻辑删除'
) COMMENT '系统角色表';

-- 用户角色关联表
CREATE TABLE TB_S_USER_ROLE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '主键',
    USER_ID VARCHAR(32) NOT NULL COMMENT '用户 ID',
    ROLE_ID VARCHAR(32) NOT NULL COMMENT '角色 ID',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间'
) COMMENT '用户角色关联表';

-- 班级表
CREATE TABLE TB_B_BASE_CLASS (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '班级 ID',
    CLASS_NAME VARCHAR(100) NOT NULL COMMENT '班级名称',
    SCHOOL_ID VARCHAR(32) COMMENT '学校 ID',
    GRADE VARCHAR(10) COMMENT '年级',
    TEACHER_ID VARCHAR(32) COMMENT '班主任 ID',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间',
    GXR VARCHAR(32) COMMENT '更新人',
    GXSJ DATETIME COMMENT '更新时间',
    LJSC INT DEFAULT 0 COMMENT '逻辑删除'
) COMMENT '班级信息表';

-- 作业主表
CREATE TABLE TB_B_HOMEWORK (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '作业 ID',
    TITLE VARCHAR(200) NOT NULL COMMENT '作业标题',
    SUBJECT VARCHAR(50) NOT NULL COMMENT '学科',
    TYPE VARCHAR(50) NOT NULL COMMENT '作业类型',
    PUBLISH_DATE DATE COMMENT '布置日期',
    DEADLINE DATETIME COMMENT '截止时间',
    DURATION INT COMMENT '预计时长 (分钟)',
    DESCRIPTION VARCHAR(1000) COMMENT '作业描述',
    STATUS VARCHAR(10) DEFAULT 'WKS' COMMENT '状态：WKS 未开始/JXZ 进行中/YJZ 已截止/YWC 已完成',
    TEACHER_ID VARCHAR(32) NOT NULL COMMENT '发布教师 ID',
    TEACHER_NAME VARCHAR(100) COMMENT '发布教师姓名',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间',
    GXR VARCHAR(32) COMMENT '更新人',
    GXSJ DATETIME COMMENT '更新时间',
    LJSC INT DEFAULT 0 COMMENT '逻辑删除'
) COMMENT '作业信息表';

-- 作业班级关联表
CREATE TABLE TB_B_HOMEWORK_CLASS (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '主键',
    HOMEWORK_ID VARCHAR(32) NOT NULL COMMENT '作业 ID',
    CLASS_ID VARCHAR(32) NOT NULL COMMENT '班级 ID',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间'
) COMMENT '作业班级关联表';

-- 题库表
CREATE TABLE TB_B_QUESTION (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '题目 ID',
    TITLE VARCHAR(1000) NOT NULL COMMENT '题目标题',
    SUBJECT VARCHAR(50) COMMENT '学科',
    TYPE VARCHAR(50) COMMENT '题型',
    DIFFICULTY VARCHAR(20) COMMENT '难度',
    KNOWLEDGE VARCHAR(200) COMMENT '知识点',
    CONTENT TEXT COMMENT '题目内容',
    ANSWER TEXT COMMENT '参考答案',
    SCORE DECIMAL(5,2) DEFAULT 5.00 COMMENT '默认分值',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间',
    GXR VARCHAR(32) COMMENT '更新人',
    GXSJ DATETIME COMMENT '更新时间',
    LJSC INT DEFAULT 0 COMMENT '逻辑删除'
) COMMENT '题库信息表';

-- 作业题目关联表
CREATE TABLE TB_B_HOMEWORK_QUESTION (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '主键',
    HOMEWORK_ID VARCHAR(32) NOT NULL COMMENT '作业 ID',
    QUESTION_ID VARCHAR(32) NOT NULL COMMENT '题目 ID',
    SCORE DECIMAL(5,2) COMMENT '本题分值',
    PX INT DEFAULT 0 COMMENT '排序',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间'
) COMMENT '作业题目关联表';

-- 作业提交表
CREATE TABLE TB_B_HOMEWORK_SUBMIT (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '提交 ID',
    HOMEWORK_ID VARCHAR(32) NOT NULL COMMENT '作业 ID',
    STUDENT_ID VARCHAR(32) NOT NULL COMMENT '学生 ID',
    STUDENT_NAME VARCHAR(100) COMMENT '学生姓名',
    CLASS_ID VARCHAR(32) COMMENT '班级 ID',
    ANSWER_CONTENT TEXT COMMENT '答案内容',
    FILE_URL VARCHAR(500) COMMENT '上传文件 URL',
    DESCRIPTION VARCHAR(500) COMMENT '备注说明',
    SUBMIT_TIME DATETIME COMMENT '提交时间',
    AI_STATUS VARCHAR(20) DEFAULT 'WAITING' COMMENT 'AI 判分状态',
    AI_SCORE DECIMAL(5,2) COMMENT 'AI 判分',
    STATUS VARCHAR(10) DEFAULT 'YTI' COMMENT '状态：WTJ 未提交/YTI 已提交/YPY 待批阅/YQR 已确认',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间',
    GXR VARCHAR(32) COMMENT '更新人',
    GXSJ DATETIME COMMENT '更新时间'
) COMMENT '作业提交表';

-- 作业批阅表
CREATE TABLE TB_B_HOMEWORK_GRADE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '批阅 ID',
    SUBMIT_ID VARCHAR(32) NOT NULL COMMENT '提交 ID',
    HOMEWORK_ID VARCHAR(32) NOT NULL COMMENT '作业 ID',
    STUDENT_ID VARCHAR(32) NOT NULL COMMENT '学生 ID',
    SCORE DECIMAL(5,2) COMMENT '得分',
    COMMENT TEXT COMMENT '教师评语',
    GRADE_TEACHER_ID VARCHAR(32) COMMENT '批阅教师 ID',
    GRADE_TEACHER_NAME VARCHAR(100) COMMENT '批阅教师姓名',
    GRADE_TIME DATETIME COMMENT '批阅时间',
    CJR VARCHAR(32) COMMENT '创建人',
    CJSJ DATETIME COMMENT '创建时间',
    GXR VARCHAR(32) COMMENT '更新人',
    GXSJ DATETIME COMMENT '更新时间'
) COMMENT '作业批阅表';
